routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\ItemCategorys;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
// Route::get('/register', function () {
//   // abort(404);
// });

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/excel', 'UserController@excel')->name('user.excel');
Route::get('/report/monstersDefault', 'MonstersDefaultController@report')->name('report.monstersDefault');
Route::get('/monstersDefault/excel', 'MonstersDefaultController@excel')->name('monstersDefault.excel');
Route::get('/monstersDefault/{id}/player', 'MonstersDefaultController@player')->name('player');
Route::get('/report/wildMonsters', 'WildMonstersController@report')->name('report.wildMonsters');
Route::get('/wildMonsters/excel', 'WildMonstersController@excel')->name('wildMonsters.excel');
Route::get('/wildMonsters/excelIndex', 'WildMonstersController@excelIndex')->name('wildMonsters.excelIndex');
Route::get('/wildMonstersInstantiate/excel', 'WildMonstersController@excelInstantiate')->name('monstersInstantiate.excel');
Route::get('/report/monstersInstantiate', 'WildMonstersController@instantiate')->name('report.monstersInstantiate');
Route::get('/report/itemPlayer', 'ItemPlayerController@report')->name('report.itemPlayer');
Route::get('/report/itemCoupon', 'ItemPlayerController@itemCoupon')->name('report.itemCoupon');
Route::get('/report/itemCouponExcel', 'ItemPlayerController@itemCouponExcel')->name('itemCoupon.excel');
Route::get('/itemPlayer/excel', 'ItemPlayerController@excel')->name('itemPlayer.excel');
Route::get('/report/monsterInShop', 'MonstersInShopController@report')->name('report.monsterInShop');
Route::get('/monsterInShop/excel', 'MonstersInShopController@excel')->name('monsterInShop.excel');
Route::post('/itemPlayer/search', 'ItemPlayerController@search')->name('search');
Route::get('/privilegeShops/excel', 'PrivilegeShopsController@excel')->name('privilegeShops.excel');
Route::post('/privilegeShops/search', 'PrivilegeShopsController@search')->name('privilegeShops.search');
Route::get('/shops/excelPrivilegeShops', 'ShopsController@excelPrivilegeShops')->name('shops.excelPrivilegeShops');
Route::get('/shops/excelPromotion', 'ShopsController@excelPromotion')->name('shops.excelPromotion');
Route::post('/shops/searchIndex', 'ShopsController@searchIndex')->name('shops.searchIndex');
Route::get('/playerLogs/excel', 'PlayerLogsController@excel')->name('playerLogs.excel');
Route::get('/activities/calender', 'ActivitiesController@calender')->name('activities.calender');
Route::get('/activities/{id}/view', 'ActivitiesController@view')->name('activities.view');
Route::get('/couponItem/importCsv', 'CouponItemController@importCsv')->name('couponItem.importCsv');
Route::post('/couponItem/storeCsv', 'CouponItemController@storeCsv')->name('couponItem.storeCsv');
Route::resource('playerLogs', 'PlayerLogsController');
Route::resource('itemPlayer', 'ItemPlayerController');
Route::resource('players', 'PlayersController');
Route::resource('itemDefaults', 'ItemDefaultsController');
Route::resource('itemCategorys', 'ItemCategorysController');
Route::post('/news/search', 'NewsController@search')->name('news.search');
Route::resource('news', 'NewsController');
Route::get('/news/push/{id}', 'NewsController@push')->name('push');
Route::resource('newsTypes', 'NewsTypesController');
Route::resource('malls', 'MallsController');
Route::resource('shops', 'ShopsController');
Route::resource('shopAds', 'ShopAdsController');
Route::resource('shopAsserts', 'ShopAssertsController');
Route::resource('shopCategories', 'ShopCategoriesController');
Route::resource('zoneTypes', 'ZoneTypeController');
Route::resource('stickerStores', 'StickerStoreController');
Route::resource('authenTypes', 'AuthenTypeController');
Route::resource('mallFloors', 'MallFloorsController');
Route::resource('costumes', 'CostumesController');
Route::resource('digitalBoardAsserts', 'DigitalBoardAssertsController');
Route::resource('wildItems', 'WildItemsController');
Route::resource('wildMonsters', 'WildMonstersController');
Route::resource('testUpload', 'TestUploadController');
Route::resource('privilegeDefaults', 'PrivilegeDefaultsController');
Route::resource('monstersDefaultsTypes', 'MonstersDefaultsTypesController');
Route::resource('monstersDefault', 'MonstersDefaultController');
Route::resource('privilegeGroups', 'PrivilegeGroupsController');
Route::resource('privilegeShops', 'PrivilegeShopsController');
Route::resource('monsterInShop', 'MonstersInShopController');
Route::resource('user', 'UserController');
Route::resource('mailBox', 'MailBoxController');
Route::get('/mailBox/push/{id}', 'MailBoxController@push')->name('push');
Route::resource('digitalBoard', 'DigitalBoardController');
Route::delete('/digitalBoard/deleteThumbnail/{id}/{image}/{type}', 'DigitalBoardController@deleteThumbnail');
Route::resource('monstersPlayer', 'MonstersPlayerController');
Route::get('/privacyPolicy/view/', 'PrivacyPolicyController@view')->name('privacyPolicy.view');
Route::get('/privacyPolicy/{version}/setupCurrent', 'PrivacyPolicyController@setupCurrent')->name('privacyPolicy.setupCurrent');
Route::resource('privacyPolicy', 'PrivacyPolicyController');
Route::resource('device', 'DeviceController');
Route::get('device/{id}/view', 'DeviceController@view')->name('view');
Route::resource('loginReward', 'LoginRewardController');
Route::get('thumbnail/edit', 'ThumbnailImageController@edit')->name('edit');
Route::put('thumbnail/setImage', 'ThumbnailImageController@setImage')->name('setImage');
Route::get('giveMonster/edit', 'GiveMonsterController@edit')->name('edit');
Route::resource('giveMonster', 'GiveMonsterController');
Route::resource('thumbnail', 'ThumbnailImageController');
Route::resource('roles', 'RoleController');
Route::get('genCouponPassword/{json}', function ($json) {
    $code = "{\"\couponPassword\"\:{$json}";
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});

Route::get('genCouponPassword/{json}', function ($json) {
    $code = '{"couponPassword":"' . $json . '"}';
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});
Route::get('genQrCode/{code}', function ($code) {

    \QrCode::size(250)
        ->format('png')
        ->generate($code);
    return view('qrCode', compact('code'));
});

Route::resource('networkAccess', 'NetworkAccessController');
Route::resource('ipAccess', 'IpAccessController');
Route::resource('partnerTypes', 'PartnerTypesController');
Route::resource('activities', 'ActivitiesController');
Route::delete('couponItem/destroyItemPlayer/{id}', 'CouponItemController@deleteItemPlayer')->name('couponItem.destroyItemPlayer');
Route::get('couponItem/createMultipleCode', 'CouponItemController@createMultipleCode')->name('couponItem.createMultipleCode');
Route::post('/couponItem/storeMultipleCode', 'CouponItemController@storeMultipleCode')->name('couponItem.storeMultipleCode');
Route::resource('couponItem', 'CouponItemController');

app/Models/Costumes.php
<?php

namespace App\Models;

// use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use App\Helper\MongoModel;
use App\Helper\NestedMongoModel;

class Costumes extends MongoModel
{
    
    protected $connection = 'mongodb';
    protected $collection = 'costumes';
    protected $guarded = [];

    public static function SCHEMAS()
    {
        return [

            'costumeName' => ['type' => 'array(string)' ],
            'costumeDetail' => ['type' => 'array(string)' ],
            'coin'       => ['type' => 'int'],
            'diamond'       => ['type' => 'int'],
            'costumesAssertVersion' => ['type' => 'int'],
            'isActive'    => ['type' => 'bool',   'default' => false],
            'custumesAssertModelIOS'=> ['type' => 'string'],
            'custumesAssertModelAndroid'=> ['type' => 'string'],
            'gender'=> ['type' => 'string'],
        
        ];
    }

}

app/Http/Controllers/CostumesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use App\Models\Costumes;
use App\Http\Requests\CostumesRequest;

class CostumesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:Resource');
    }

    public function index()
    {
        $costumes = Costumes::all();

        return view('costumes.index', compact('costumes'));
    }

    public function create()
    {
        $assertModelIOS = null;
        $assertModelAndroid = null;

        return view('costumes.create', compact('assertModelIOS', 'assertModelAndroid'));
    }

    public function store(CostumesRequest $request)
    {
        $costume = new Costumes($request->all());
        $costumeAssertModelIOS = $costume->AssertModelIOS;
        $assetIOSPath = '/public/media/ios/costumes/';
        $costumeAssertModelAndroid = $costume->AssertModelAndroid;
        $assetAndroidPath = '/public/media/android/costumes/';

        if (isset($costumeAssertModelIOS)) {
            $generateAssertModelIOS = uniqid();
            foreach ($costumeAssertModelIOS as $assertModelIOS) {
                $getAssetModelTypeIOS = $assertModelIOS->getClientOriginalExtension();
                if (!!$getAssetModelTypeIOS) {
                    $assetModelNameIOS = $generateAssertModelIOS . '.' . $getAssetModelTypeIOS;
                    $assertModelIOS->move(base_path() . $assetIOSPath, $assetModelNameIOS);
                } else {
                    $assertModelIOS->move(base_path() . $assetIOSPath, $generateAssertModelIOS);
                }
            }

            $costume->custumesAssertModelIOS = $generateAssertModelIOS;
        }



        if (isset($costumeAssertModelAndroid)) {
            $generateAssertModelAndroid = uniqid();
            foreach ($costumeAssertModelAndroid as $assertModelAndroid) {
                $getAssetModelTypeAndroid = $assertModelAndroid->getClientOriginalExtension();
                if (!!$getAssetModelTypeAndroid) {
                    $assetModelNameAndroid = $generateAssertModelAndroid . '.' . $getAssetModelTypeAndroid;
                    $assertModelAndroid->move(base_path() . $assetAndroidPath, $assetModelNameAndroid);
                } else {
                    $assertModelAndroid->move(base_path() . $assetAndroidPath, $generateAssertModelAndroid);
                }
            }
            $costume->custumesAssertModelAndroid = $generateAssertModelAndroid;
        }

        if ($costume->save()) {
            return redirect('costumes')->with('success', trans('costumes/message.success.create'));
        } else {
            return Redirect::route('costumes')->withInput()->with('error', trans('costumes/message.error.create'));
        }
    }

    public function edit(Costumes $costume)
    {
        $assertModelIOS = $costume->custumesAssertModelIOS;
        $assertModelAndroid = $costume->custumesAssertModelAndroid;

        return view('costumes.edit', compact('costume', 'assertModelIOS', 'assertModelAndroid'));
    }

    public function update(CostumesRequest $request, Costumes $costume)
    {
        if ($costume->update($request->all())) {

            $costumeAssertModelIOS = $costume->AssertModelIOS;
            $assetIOSPath = '/public/media/ios/costumes/';
            $costumeAssertModelAndroid = $costume->AssertModelAndroid;
            $assetAndroidPath = '/public/media/android/costumes/';

            if (isset($costumeAssertModelIOS)) {
                $generateAssertModelIOS = uniqid();
                foreach ($costumeAssertModelIOS as $assertModelIOS) {
                    $getAssetModelTypeIOS = $assertModelIOS->getClientOriginalExtension();
                    if (!!$getAssetModelTypeIOS) {
                        $assetModelNameIOS = $generateAssertModelIOS . '.' . $getAssetModelTypeIOS;
                        $assertModelIOS->move(base_path() . $assetIOSPath, $assetModelNameIOS);
                    } else {
                        $assertModelIOS->move(base_path() . $assetIOSPath, $generateAssertModelIOS);
                    }
                }

                $costume->update(['custumesAssertModelIOS' => $generateAssertModelIOS]);
            }



            if (isset($costumeAssertModelAndroid)) {


                $generateAssertModelAndroid = uniqid();
                foreach ($costumeAssertModelAndroid as $assertModelAndroid) {
                    $getAssetModelTypeAndroid = $assertModelAndroid->getClientOriginalExtension();
                    if (!!$getAssetModelTypeAndroid) {
                        $assetModelNameAndroid = $generateAssertModelAndroid . '.' . $getAssetModelTypeAndroid;
                        $assertModelAndroid->move(base_path() . $assetAndroidPath, $assetModelNameAndroid);
                    } else {
                        $assertModelAndroid->move(base_path() . $assetAndroidPath, $generateAssertModelAndroid);
                    }
                }
                $costume->update(['custumesAssertModelAndroid' => $generateAssertModelAndroid]);
            }

            return redirect('costumes')->with('success', trans('costumes/message.success.update'));
        } else {
            return Redirect::route('costumes')->withInput()->with('error', trans('costumes/message.error.update'));
        }
    }

    public function destroy($id)
    {
        $costume = Costumes::find($id);

        if ($costume) {
            $costume->delete();
            return redirect('costumes')->with('success', trans('costumes/message.success.destroy'));
        } else {
            return redirect('costumes')->with('error', trans('costumes/message.error.delete'));
        }
    }

    public function data()
    {
        $models = Costumes::get(['id', 'first_name', 'last_name', 'email', 'created_at']);

        return DataTables::of($models)
            ->editColumn('created_at', function (Costumes $models) {
                return $user->created_at->diffForHumans();
            })
            ->addColumn('status', function ($user) {
                if ($activation = Activation::completed($user)) {
                    return 'Activated';
                } else {
                    return 'Pending';
                }
            })
            ->addColumn('actions', function ($user) {
                $actions = '<a href=' . route('users.show', $user->id) . '><i class="livicon" data-name="info" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="view user"></i></a>
                            <a href=' . route('users.edit', $user->id) . '><i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="update user"></i></a>';
                if ((Sentinel::getUser()->id != $user->id) && ($user->id != 1)) {
                    $actions .= '<a href=' . route('users.confirm-delete', $user->id) . ' data-id="' . $user->id . '" data-toggle="modal" data-target="#delete_confirm"><i class="livicon" data-name="user-remove" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete user"></i></a>';
                }
                return $actions;
            })
            ->rawColumns(['actions'])
            ->make(true);
    }
}

resources/views/costumes/create.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop 

@section('content')
<section class="content-header">
    <h1>Costumes</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('costumes') }}"> Costumes</a></li>
        <li class="active">Add new</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Add New</h3>
            </div>
            <div class="panel-body">
                <form id="costumeForm" action="{{ route('costumes.store') }}" method="POST" enctype="multipart/form-data"
                    class="form-horizontal">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                    <fieldset>
                    @include('costumes.field')
                    </fieldset>

                </form>

            </div>
        </div>
    </div>
</section>


@stop 

resources/views/costumes/edit.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop 
@section('content')
<section class="content-header">
    <h1>Costumes</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('costumes') }}"> Costumes</a></li>
        <li class="active">Edit</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Edit</h3>
            </div>
            <div class="panel-body">
                {!! Form::model($costume, ['url' => URL::to('costumes') . '/' . $costume->id, 'method' => 'put', 'class' => 'form-horizontal', 'enctype'=>'multipart/form-data']) !!}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input type="hidden" name="isActive" value="0" />
                   
                    <fieldset>
                    @include('costumes.field')
                    </fieldset>

                {!! Form::close() !!}

            </div>
        </div>
    </div>
</section>


@stop 

resources/views/costumes/field.blade.php
@include('constants.gender')
    @component('components.multiLangField',[
        'header'=>'Costume Names',
        'field'=>'costumeName',
        'icon'=>'livicon'
        ])
    @endcomponent

    @component('components.multiLangTextAreaField',[
        'header'=>'Costume Details',
        'field'=>'costumeDetail',
        'icon'=>'livicon'
        ])
    @endcomponent
<h4>Multi</h4>
<div class="row">
    <div class="col-md-6">
        @component('components.inputField',[
            'type'=>'number',
            'icon'=>'text',
            'label'=>'Coin',
            'field'=>'coin',
            'value'=>null,
            'attribute'=>['class'=>'form-control','placeholder'=>'Coin']
        ])
        @endcomponent
    </div>
    <div class="col-md-6">
        @component('components.inputField',[
            'type'=>'number',
            'icon'=>'text',
            'label'=>'Diamond',
            'field'=>'diamond',
            'value'=>null,
            'attribute'=>['class'=>'form-control','placeholder'=>'Diamond']
        ])
        @endcomponent
    </div>
    <div class="col-md-6">
        @component('components.inputField',[
            'type'=>'checkbox',
            'label'=>'Active',
            'field'=>'isActive',
            'value'=>null,
            'attribute'=>['class'=>'form-control']
        ])
        @endcomponent
    </div>
   
    <div class="col-md-6">
        @component('components.inputField',[
            'type'=>'select',
            'label'=>'Gender',
            'field'=>'gender',
            'value'=>null,
            'data'=>$GLOBALS['genderData'],
            'attribute'=>['class'=>'form-control','placeholder'=>'Please Select']
            
        ])
        @endcomponent 
    </div>

    <div class="col-md-6">
        @component('components.inputField',[
            'type'=>'number',
            'icon'=>'text',
            'label'=>'Asset Version',
            'field'=>'costumesAssertVersion',
            'value'=>empty($costume->costumesAssertVersion)?1:$costume->costumesAssertVersion,
            'attribute'=>['class'=>'form-control','placeholder'=>'Asset Version']
        ])
        @endcomponent
    </div>
   

    <div class="col-md-12">
        @component('components.inputField',[
        'type'=>'file',
        'icon'=>'user',
        'label'=>'Assert Model IOS (Multiple)',
        'field'=>'AssertModelIOS[]',
        'value'=>$assertModelIOS,
        'attribute'=>['class'=>'form-control','multiple'=>true]
    ])
    
    @endcomponent
        
    </div>

    <div class="col-md-12">
        @component('components.inputField',[
        'type'=>'file',
        'icon'=>'user',
        'label'=>'Assert Model Android (Multiple)',
        'field'=>'AssertModelAndroid[]',
        'value'=>$assertModelAndroid,
        'attribute'=>['class'=>'form-control','multiple'=>true]
    ])
    
    @endcomponent
        
    </div>
    
</div>


    <div class="form-group">
        <div class="col-md-12 text-right">
            <button type="submit" class="btn btn-responsive btn-primary btn-sm">Submit</button>
        </div>
    </div>

resources/views/costumes/index.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Costume Lists @parent 
@stop {{-- page level styles--}}

@section('header_styles') 
@stop {{-- Page content --}} 
@section('content')
<section class="content-header">
    <h1>Costumes</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li><a href="#"> Costumes</a></li>
        <li class="active">Costume Lists</li>
    </ol>
</section>
<section class="content paddingleft_right15">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable ">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title pull-left">Costumes</h3>
                    <div class="pull-right">
                    <a href="{{ URL::to('costumes/create') }}" class="btn btn-primary btn-sm" id="addButton">Add new</a>
                    </div>
                </div>

                <div class="panel-body table-responsive">
                    <table class="table" id="table">
                        <thead>
                            <tr class="filters">
                                <th>Costume Name</th>
                                <th>Coin</th>
                                <th>Diamond</th>
                                <th>Active</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($costumes as $row)
                            <tr>
                                <td>{{ $row->costumeName['eng'] }}</td>
                                <td>{{ $row->coin }}</td>
                                <td>{{ $row->diamond }}</td>
                                <td>@if ($row->isActive)
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true" style="color:#5cb85c;font-size:16px;"></span>
                                    @else
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"style="color:#d9534f;font-size:16px;"></span>
                                    @endif
                                </td>
                                
                                
                                <td>
                                    <a href="{{{ URL::to('costumes/' . $row->id . '/edit' ) }}}">
                                        <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="Edit"></i>
                                    </a>
                                </a>
                                    <a href="#" data-toggle="modal" data-target="#delete_confirm"  data-id="{{ route('costumes.destroy', collect($row)->first()) }}">
                                    <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete user"></i>
                                </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- Modal for showing delete confirmation -->
                    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="user_delete_confirm_title">
                                        Delete
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure to delete this?
                                </div>
                                <div class="modal-footer">
                                {!! Form::open(['method' => 'DELETE']) !!}
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                                    <button type="submit" class="btn btn-danger">Delete</a>
                                {!! Form::close() !!} 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>



@stop {{-- page level scripts --}} 
@section('footer_scripts')
<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/jquery.dataTables.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
<script>
    $(document).ready(function() {
        $('#table').dataTable({
            "pageLength": 50
        });
    });
    $('#delete_confirm').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget)
        let $recipient = button.data('id');
        console.log("recipient: ",$recipient);

        let modal = $(this);
        modal.find('.modal-footer form').prop("action",$recipient);
    });

</script>
@stop