routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\ItemCategorys;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
// Route::get('/register', function () {
//   // abort(404);
// });

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/excel', 'UserController@excel')->name('user.excel');
Route::get('/report/monstersDefault', 'MonstersDefaultController@report')->name('report.monstersDefault');
Route::get('/monstersDefault/excel', 'MonstersDefaultController@excel')->name('monstersDefault.excel');
Route::get('/monstersDefault/{id}/player', 'MonstersDefaultController@player')->name('player');
Route::get('/report/wildMonsters', 'WildMonstersController@report')->name('report.wildMonsters');
Route::get('/wildMonsters/excel', 'WildMonstersController@excel')->name('wildMonsters.excel');
Route::get('/wildMonsters/excelIndex', 'WildMonstersController@excelIndex')->name('wildMonsters.excelIndex');
Route::get('/wildMonstersInstantiate/excel', 'WildMonstersController@excelInstantiate')->name('monstersInstantiate.excel');
Route::get('/report/monstersInstantiate', 'WildMonstersController@instantiate')->name('report.monstersInstantiate');
Route::get('/report/itemPlayer', 'ItemPlayerController@report')->name('report.itemPlayer');
Route::get('/report/itemCoupon', 'ItemPlayerController@itemCoupon')->name('report.itemCoupon');
Route::get('/report/itemCouponExcel', 'ItemPlayerController@itemCouponExcel')->name('itemCoupon.excel');
Route::get('/itemPlayer/excel', 'ItemPlayerController@excel')->name('itemPlayer.excel');
Route::get('/report/monsterInShop', 'MonstersInShopController@report')->name('report.monsterInShop');
Route::get('/monsterInShop/excel', 'MonstersInShopController@excel')->name('monsterInShop.excel');
Route::post('/itemPlayer/search', 'ItemPlayerController@search')->name('search');
Route::get('/privilegeShops/excel', 'PrivilegeShopsController@excel')->name('privilegeShops.excel');
Route::post('/privilegeShops/search', 'PrivilegeShopsController@search')->name('privilegeShops.search');
Route::get('/shops/excelPrivilegeShops', 'ShopsController@excelPrivilegeShops')->name('shops.excelPrivilegeShops');
Route::get('/shops/excelPromotion', 'ShopsController@excelPromotion')->name('shops.excelPromotion');
Route::post('/shops/searchIndex', 'ShopsController@searchIndex')->name('shops.searchIndex');
Route::get('/playerLogs/excel', 'PlayerLogsController@excel')->name('playerLogs.excel');
Route::get('/activities/calender', 'ActivitiesController@calender')->name('activities.calender');
Route::get('/activities/{id}/view', 'ActivitiesController@view')->name('activities.view');
Route::get('/couponItem/importCsv', 'CouponItemController@importCsv')->name('couponItem.importCsv');
Route::post('/couponItem/storeCsv', 'CouponItemController@storeCsv')->name('couponItem.storeCsv');
Route::resource('playerLogs', 'PlayerLogsController');
Route::resource('itemPlayer', 'ItemPlayerController');
Route::resource('players', 'PlayersController');
Route::resource('itemDefaults', 'ItemDefaultsController');
Route::resource('itemCategorys', 'ItemCategorysController');
Route::post('/news/search', 'NewsController@search')->name('news.search');
Route::resource('news', 'NewsController');
Route::get('/news/push/{id}', 'NewsController@push')->name('push');
Route::resource('newsTypes', 'NewsTypesController');
Route::resource('malls', 'MallsController');
Route::resource('shops', 'ShopsController');
Route::resource('shopAds', 'ShopAdsController');
Route::resource('shopAsserts', 'ShopAssertsController');
Route::resource('shopCategories', 'ShopCategoriesController');
Route::resource('zoneTypes', 'ZoneTypeController');
Route::resource('stickerStores', 'StickerStoreController');
Route::resource('authenTypes', 'AuthenTypeController');
Route::resource('mallFloors', 'MallFloorsController');
Route::resource('costumes', 'CostumesController');
Route::resource('digitalBoardAsserts', 'DigitalBoardAssertsController');
Route::resource('wildItems', 'WildItemsController');
Route::resource('wildMonsters', 'WildMonstersController');
Route::resource('testUpload', 'TestUploadController');
Route::resource('privilegeDefaults', 'PrivilegeDefaultsController');
Route::resource('monstersDefaultsTypes', 'MonstersDefaultsTypesController');
Route::resource('monstersDefault', 'MonstersDefaultController');
Route::resource('privilegeGroups', 'PrivilegeGroupsController');
Route::resource('privilegeShops', 'PrivilegeShopsController');
Route::resource('monsterInShop', 'MonstersInShopController');
Route::resource('user', 'UserController');
Route::resource('mailBox', 'MailBoxController');
Route::get('/mailBox/push/{id}', 'MailBoxController@push')->name('push');
Route::resource('digitalBoard', 'DigitalBoardController');
Route::delete('/digitalBoard/deleteThumbnail/{id}/{image}/{type}', 'DigitalBoardController@deleteThumbnail');
Route::resource('monstersPlayer', 'MonstersPlayerController');
Route::get('/privacyPolicy/view/', 'PrivacyPolicyController@view')->name('privacyPolicy.view');
Route::get('/privacyPolicy/{version}/setupCurrent', 'PrivacyPolicyController@setupCurrent')->name('privacyPolicy.setupCurrent');
Route::resource('privacyPolicy', 'PrivacyPolicyController');
Route::resource('device', 'DeviceController');
Route::get('device/{id}/view', 'DeviceController@view')->name('view');
Route::resource('loginReward', 'LoginRewardController');
Route::get('thumbnail/edit', 'ThumbnailImageController@edit')->name('edit');
Route::put('thumbnail/setImage', 'ThumbnailImageController@setImage')->name('setImage');
Route::get('giveMonster/edit', 'GiveMonsterController@edit')->name('edit');
Route::resource('giveMonster', 'GiveMonsterController');
Route::resource('thumbnail', 'ThumbnailImageController');
Route::resource('roles', 'RoleController');
Route::get('genCouponPassword/{json}', function ($json) {
    $code = "{\"\couponPassword\"\:{$json}";
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});

Route::get('genCouponPassword/{json}', function ($json) {
    $code = '{"couponPassword":"' . $json . '"}';
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});
Route::get('genQrCode/{code}', function ($code) {

    \QrCode::size(250)
        ->format('png')
        ->generate($code);
    return view('qrCode', compact('code'));
});

Route::resource('networkAccess', 'NetworkAccessController');
Route::resource('ipAccess', 'IpAccessController');
Route::resource('partnerTypes', 'PartnerTypesController');
Route::resource('activities', 'ActivitiesController');
Route::delete('couponItem/destroyItemPlayer/{id}', 'CouponItemController@deleteItemPlayer')->name('couponItem.destroyItemPlayer');
Route::get('couponItem/createMultipleCode', 'CouponItemController@createMultipleCode')->name('couponItem.createMultipleCode');
Route::post('/couponItem/storeMultipleCode', 'CouponItemController@storeMultipleCode')->name('couponItem.storeMultipleCode');
Route::resource('couponItem', 'CouponItemController');

app/Http/Controllers/IpAccessController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Models\NetworkAccess;
use App\Models\IpAccess;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;

class IpAccessController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:Setting_Resource');
    }

    public function index()
    {
        $ipAccess = IpAccess::with(['networkaccess'])->get()->toArray();

        return view('ipAccess.index', compact('ipAccess'));
    }

    public function create()
    {
        $networkAccess = NetworkAccess::queryNetworkAccess();
        $networkAccessId = Input::get('networkAccessId');
        return view('ipAccess.create', compact('networkAccess', 'networkAccessId'));
    }
    public function store(Request $request)
    {
        $model = new IpAccess($request->all());
        if ($model->save()) {

            return redirect('ipAccess/' . $model->id . '/edit')->with('success', 'Success create');
        } else {
            return Redirect::route('ipAccess')->withInput()->with('error', trans('malls/message.error.create'));
        }
    }

    public function edit(IpAccess $ipAccess)
    {
        $networkAccess = NetworkAccess::queryNetworkAccess();
        $networkAccessId = $ipAccess->networkAccessId;
        return view('ipAccess.edit', compact('ipAccess', 'networkAccess', 'networkAccessId'));
    }


    public function update(Request $request, IpAccess $ipAccess)
    {
        if ($ipAccess->update($request->all())) {
            return redirect('ipAccess/' . $ipAccess->id . '/edit')->with('success', 'Success Update');
        } else {
            return Redirect::route('ipAccess')->withInput()->with('error', trans('malls/message.error.create'));
        }
    }

    public function destroy($id)
    {

        $ipAccess = IpAccess::find($id);

        if ($ipAccess) {
            $ipAccess->delete();
            return redirect('networkAccess/' . $ipAccess->networkAccessId . '/edit')->with('success', trans('Success delete IpAddress'));
        } else {
            return redirect('ipAccess')->with('error', trans('ipAccess/message.error.delete'));
        }
    }
}

resources/views/ipAccess/create.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop
@section('content')
<section class="content-header">
    <h1>Ip Access</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('ipAccess') }}"> Ip Access</a></li>
        <li class="active">Add new</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h4 class="panel-title">Add New</h4>
            </div>
            <div class="panel-body">
                <form id="ipAccessForm" action="{{ route('ipAccess.store') }}" method="POST" enctype="multipart/form-data"
                    class="form-horizontal">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                    <fieldset>
                    @include('ipAccess.field')
                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</section>

@stop 

resources/views/ipAccess/edit.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop 
@section('content')
<section class="content-header">
    <h1>Ip Access</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('ipAccess') }}"> Ip Access</a></li>
        <li class="active">Edit</li>
    </ol>
</section>


@if ($message = Session::get('success'))
<section class="content paddingleft_right15">
    <div class="row">   
        <div class="panel panel-success filterable">
                <div class="panel-heading">
                    <h3 class="panel-title">{{$message}}</h3>
                </div>
        </div>
    </div>
</section>
@endif

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h4 class="panel-title">Edit</h4>
            </div>
            <div class="panel-body">
                    {!! Form::model($ipAccess, ['url' => URL::to('ipAccess') . '/' . $ipAccess->id, 'method' => 'put', 'class' => 'form-horizontal', 'enctype'=>'multipart/form-data']) !!}
                    <input type="hidden" name="isActive" value="0" />

                    <fieldset>
                    @include('ipAccess.field')
                    </fieldset>
                
                    {!! Form::close() !!}

            </div>
        </div>
    </div>
</section>

@stop 

resources/views/ipAccess/field.blade.php
<div class="row">
        <div class="col-md-9">
            @component('components.inputField',[
                'type'=>'select',
                'label'=>'NetworkAccess',
                'field'=>'networkAccessId',
                'value'=>$networkAccessId,
                'data'=>$networkAccess,
                'attribute'=>['class'=>'form-control','placeholder'=>'Please Select']
            ])
            @endcomponent
        </div>
        <div class="col-md-9">
            @component('components.inputField',[
            'type'=>'text',
            'label'=>'Ip Name',
            'field'=>'ipName',
            'icon'=>'icon',
            'value'=>null,
            'attribute'=>['class'=>'form-control','placeholder'=>'Ip Name']
            ])
            @endcomponent
        </div>
        <div class="col-md-9">
            @component('components.inputField',[
            'type'=>'text',
            'label'=>'Ip Address',
            'field'=>'ipAddress',
            'icon'=>'icon',
            'value'=>isset($ipAccess->ipAddress)?null:$_SERVER['REMOTE_ADDR'],
            'attribute'=>['class'=>'form-control','placeholder'=>'Ip Address']
            ])
            @endcomponent
        </div>

        
    <div class="col-md-9">
        @component('components.inputField',[
            'type'=>'checkbox',
            'icon'=>'text',
            'label'=>'Active',
            'field'=>'isActive',
            'value'=>isset($ipAccess->isActive)?null:true, 
            'attribute'=>['class'=>'form-control']
        ])
        @endcomponent
    </div>

        <div class="form-group">
            <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-responsive btn-primary btn-sm">Submit</button>
            </div>
        </div>
</div>

resources/views/ipAccess/index.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') IP Access Lists @parent 
@stop {{-- page level styles--}}

@section('header_styles') 

@stop {{-- Page content --}} 
@section('content')
<section class="content-header">
    <h1>IP Access</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li><a href="#"> IP Access</a></li>
        <li class="active">IP Access Lists</li>
    </ol>
</section>
<section class="content paddingleft_right15">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable ">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title pull-left">IP Access</h3>
                    <div class="pull-right">
                    <a href="{{ URL::to('ipAccess/create') }}" class="btn btn-primary btn-sm" id="addButton">Add new</a>
                    </div>
                </div>

                <div class="panel-body table-responsive">
                    <table class="table">
                        <thead>
                            <tr class="filters">
                                <th>Ip Access</th>
                                <th>Server</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            @foreach($ipAccess  as $row)
                            <tr>
                                <td>{{$row['ipAddress']}}</td>
                                <td>{{$row['networkaccess']['server']}}</td>
                                <td>
                                <a href="{{ URL::to('ipAccess/' . $row['_id'] . '/edit' ) }}">
                                    <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="Edit"></i>
                                </a>
                                <a href="#" data-toggle="modal" data-target="#delete_confirm"  data-id="{{ route('monstersDefault.destroy', collect($row)->first()) }}">
                                    <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete user"></i>
                                </a>
                                
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- Modal for showing delete confirmation -->
                    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="user_delete_confirm_title">
                                        Delete
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure to delete this? 
                                </div>
                                <div class="modal-footer">
                                {!! Form::open(['method' => 'DELETE']) !!}
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                                    <button type="submit" class="btn btn-danger">Delete</a>
                                {!! Form::close() !!}                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>



@stop {{-- page level scripts --}} 
@section('footer_scripts')
<script>$(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});</script>

<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/jquery.dataTables.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
<script>
    $(document).ready(function() {
        $('#table').dataTable({
            "pageLength": 50
        });
    });

    $('#delete_confirm').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget)
        let $recipient = button.data('id');

        let modal = $(this);
        modal.find('.modal-footer form').prop("action",$recipient);
    })
    
</script>







@stop