routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\ItemCategorys;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
// Route::get('/register', function () {
//   // abort(404);
// });

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/excel', 'UserController@excel')->name('user.excel');
Route::get('/report/monstersDefault', 'MonstersDefaultController@report')->name('report.monstersDefault');
Route::get('/monstersDefault/excel', 'MonstersDefaultController@excel')->name('monstersDefault.excel');
Route::get('/monstersDefault/{id}/player', 'MonstersDefaultController@player')->name('player');
Route::get('/report/wildMonsters', 'WildMonstersController@report')->name('report.wildMonsters');
Route::get('/wildMonsters/excel', 'WildMonstersController@excel')->name('wildMonsters.excel');
Route::get('/wildMonsters/excelIndex', 'WildMonstersController@excelIndex')->name('wildMonsters.excelIndex');
Route::get('/wildMonstersInstantiate/excel', 'WildMonstersController@excelInstantiate')->name('monstersInstantiate.excel');
Route::get('/report/monstersInstantiate', 'WildMonstersController@instantiate')->name('report.monstersInstantiate');
Route::get('/report/itemPlayer', 'ItemPlayerController@report')->name('report.itemPlayer');
Route::get('/report/itemCoupon', 'ItemPlayerController@itemCoupon')->name('report.itemCoupon');
Route::get('/report/itemCouponExcel', 'ItemPlayerController@itemCouponExcel')->name('itemCoupon.excel');
Route::get('/itemPlayer/excel', 'ItemPlayerController@excel')->name('itemPlayer.excel');
Route::get('/report/monsterInShop', 'MonstersInShopController@report')->name('report.monsterInShop');
Route::get('/monsterInShop/excel', 'MonstersInShopController@excel')->name('monsterInShop.excel');
Route::post('/itemPlayer/search', 'ItemPlayerController@search')->name('search');
Route::get('/privilegeShops/excel', 'PrivilegeShopsController@excel')->name('privilegeShops.excel');
Route::post('/privilegeShops/search', 'PrivilegeShopsController@search')->name('privilegeShops.search');
Route::get('/shops/excelPrivilegeShops', 'ShopsController@excelPrivilegeShops')->name('shops.excelPrivilegeShops');
Route::get('/shops/excelPromotion', 'ShopsController@excelPromotion')->name('shops.excelPromotion');
Route::post('/shops/searchIndex', 'ShopsController@searchIndex')->name('shops.searchIndex');
Route::get('/playerLogs/excel', 'PlayerLogsController@excel')->name('playerLogs.excel');
Route::get('/activities/calender', 'ActivitiesController@calender')->name('activities.calender');
Route::get('/activities/{id}/view', 'ActivitiesController@view')->name('activities.view');
Route::get('/couponItem/importCsv', 'CouponItemController@importCsv')->name('couponItem.importCsv');
Route::post('/couponItem/storeCsv', 'CouponItemController@storeCsv')->name('couponItem.storeCsv');
Route::resource('playerLogs', 'PlayerLogsController');
Route::resource('itemPlayer', 'ItemPlayerController');
Route::resource('players', 'PlayersController');
Route::resource('itemDefaults', 'ItemDefaultsController');
Route::resource('itemCategorys', 'ItemCategorysController');
Route::post('/news/search', 'NewsController@search')->name('news.search');
Route::resource('news', 'NewsController');
Route::get('/news/push/{id}', 'NewsController@push')->name('push');
Route::resource('newsTypes', 'NewsTypesController');
Route::resource('malls', 'MallsController');
Route::resource('shops', 'ShopsController');
Route::resource('shopAds', 'ShopAdsController');
Route::resource('shopAsserts', 'ShopAssertsController');
Route::resource('shopCategories', 'ShopCategoriesController');
Route::resource('zoneTypes', 'ZoneTypeController');
Route::resource('stickerStores', 'StickerStoreController');
Route::resource('authenTypes', 'AuthenTypeController');
Route::resource('mallFloors', 'MallFloorsController');
Route::resource('costumes', 'CostumesController');
Route::resource('digitalBoardAsserts', 'DigitalBoardAssertsController');
Route::resource('wildItems', 'WildItemsController');
Route::resource('wildMonsters', 'WildMonstersController');
Route::resource('testUpload', 'TestUploadController');
Route::resource('privilegeDefaults', 'PrivilegeDefaultsController');
Route::resource('monstersDefaultsTypes', 'MonstersDefaultsTypesController');
Route::resource('monstersDefault', 'MonstersDefaultController');
Route::resource('privilegeGroups', 'PrivilegeGroupsController');
Route::resource('privilegeShops', 'PrivilegeShopsController');
Route::resource('monsterInShop', 'MonstersInShopController');
Route::resource('user', 'UserController');
Route::resource('mailBox', 'MailBoxController');
Route::get('/mailBox/push/{id}', 'MailBoxController@push')->name('push');
Route::resource('digitalBoard', 'DigitalBoardController');
Route::delete('/digitalBoard/deleteThumbnail/{id}/{image}/{type}', 'DigitalBoardController@deleteThumbnail');
Route::resource('monstersPlayer', 'MonstersPlayerController');
Route::get('/privacyPolicy/view/', 'PrivacyPolicyController@view')->name('privacyPolicy.view');
Route::get('/privacyPolicy/{version}/setupCurrent', 'PrivacyPolicyController@setupCurrent')->name('privacyPolicy.setupCurrent');
Route::resource('privacyPolicy', 'PrivacyPolicyController');
Route::resource('device', 'DeviceController');
Route::get('device/{id}/view', 'DeviceController@view')->name('view');
Route::resource('loginReward', 'LoginRewardController');
Route::get('thumbnail/edit', 'ThumbnailImageController@edit')->name('edit');
Route::put('thumbnail/setImage', 'ThumbnailImageController@setImage')->name('setImage');
Route::get('giveMonster/edit', 'GiveMonsterController@edit')->name('edit');
Route::resource('giveMonster', 'GiveMonsterController');
Route::resource('thumbnail', 'ThumbnailImageController');
Route::resource('roles', 'RoleController');
Route::get('genCouponPassword/{json}', function ($json) {
    $code = "{\"\couponPassword\"\:{$json}";
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});

Route::get('genCouponPassword/{json}', function ($json) {
    $code = '{"couponPassword":"' . $json . '"}';
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});
Route::get('genQrCode/{code}', function ($code) {

    \QrCode::size(250)
        ->format('png')
        ->generate($code);
    return view('qrCode', compact('code'));
});

Route::resource('networkAccess', 'NetworkAccessController');
Route::resource('ipAccess', 'IpAccessController');
Route::resource('partnerTypes', 'PartnerTypesController');
Route::resource('activities', 'ActivitiesController');
Route::delete('couponItem/destroyItemPlayer/{id}', 'CouponItemController@deleteItemPlayer')->name('couponItem.destroyItemPlayer');
Route::get('couponItem/createMultipleCode', 'CouponItemController@createMultipleCode')->name('couponItem.createMultipleCode');
Route::post('/couponItem/storeMultipleCode', 'CouponItemController@storeMultipleCode')->name('couponItem.storeMultipleCode');
Route::resource('couponItem', 'CouponItemController');

app/Models/MailBox.php
<?php

namespace App\Models;

// use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use App\Helper\MongoModel;
use App\Helper\NestedMongoModel;

class MailBox extends MongoModel
{
    protected $connection = 'mongodb';
    protected $collection = 'mailBox';
    protected $guarded = [];

    public static function SCHEMAS()
    {
        return [
            'title' => ['type' => 'string'],
            'detail' => ['type' => 'string'],
            'linkListName' => ['type' => 'string'],
            'url' => ['type' => 'string', 'default' => ""],
            'coin' => ['type' => 'int', 'default' => 0],
            'coinActive' => ['type' => 'bool', 'default' => false],
            'diamond' => ['type' => 'int', 'default' => 0],
            'diamondActive' => ['type' => 'bool', 'default' => false],
            'imageName' => ['type' => 'string', 'default' => ""],
            'thumbnail' => ['type' => 'string', 'default' => ""],
            'itemId' => ['type' => 'objectid'],
            'itemActive' => ['type' => 'bool', 'default' => false],
            'mDefaultId' => ['type' => 'objectid'],
            'monsterActive' => ['type' => 'bool', 'default' => false],
            'userId' => ['type' => 'objectid'],
            'playerId' => ['type' => 'objectid'],
            'isActive'    => ['type' => 'bool', 'default' => false],
            'createAt'    => ['type' => 'datetime',]
        ];
    }
}

app/Http/Controllers/MailBoxController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ItemDefault;
use App\Models\MonstersDefault;
use App\Models\PrivilegeDefaults;
use App\Models\UserPlayer;
use App\Models\Players;
use App\Models\MailBox;
use App\Models\PrivilegeGroups;
use App\Models\Malls;
use App\Models\MallFloor;
use App\Models\News;
use App\Models\Shops;
use App\Http\Requests\MailBoxsRequest;
use App\Helper\Thumbnail;
use App\Models\Setting;

class MailBoxController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:Promotion_Resource');
    }

    public function index()
    {
        $search = "";
        $mailBox = MailBox::raw(function ($collection) use ($search) {
            return $collection->aggregate(
                array(
                    array('$lookup' => array(
                        'from' => 'users',
                        'localField' => 'userId',
                        'foreignField' => '_id',
                        'as' => 'user'
                    )),
                    array('$unwind' => '$user'),
                )
            );
        });
        return view('mailBox.index', compact('mailBox'));
    }
    public function create()
    {
        $player = UserPlayer::getUser();
        $privilegeGroups = PrivilegeGroups::queryPrivilegeGroups();
        $privilegeDefaults = PrivilegeDefaults::queryPrivilegeDefaults();
        $itemDefaults = ItemDefault::queryItem();
        $monsterDefaults = MonstersDefault::queryMonstersDefault();
        $malls = Malls::queryMall();
        $mallFloors = MallFloor::queryMallFloors();
        $shops = Shops::queryShop();
        $news = News::queryNews();
        return view('mailBox.create', compact(
            'itemDefaults',
            'monsterDefaults',
            'privilegeDefaults',
            'privilegeGroups',
            'player',
            'malls',
            'mallFloors',
            'shops',
            'news'
        ));
    }

    public function edit(MailBox $mailBox)
    {
        $privilegeGroups = PrivilegeGroups::queryPrivilegeGroups();
        $privilegeDefaults =  PrivilegeDefaults::queryPrivilegeDefaults();
        $itemDefaults = ItemDefault::queryItem();
        $monsterDefaults = MonstersDefault::queryMonstersDefault();
        $player = UserPlayer::getUser();

        return view('mailBox.edit', compact('mailBox', 'itemDefaults', 'monsterDefaults', 'privilegeDefaults', 'privilegeGroups', 'player'));
    }

    public function update(MailBoxsRequest $request, MailBox $mailBox)
    {
        if ($mailBox->update($request->all())) {
            return redirect('mailBox/' . $mailBox->id . '/edit')->with('success', 'update mailBox Success');;
        } else {
            return redirect('mailBox/')->withInput();
        }
    }


    public function getUser()
    {
        $query = UserPlayer::raw(function ($collection) {
            return $collection->aggregate(
                array(
                    array('$lookup' => array(
                        'from' => 'players',
                        'localField' => '_id',
                        'foreignField' => 'userId',
                        'as' => 'players'
                    )),
                    array('$unwind' => '$players'),
                )
            );
        });
        $arr = [];
        if ($query) {
            foreach ($query as $data) {
                $arr[$data->id] = $data->email;
            }
        }

        return $arr;
    }

    public function store(MailBoxsRequest $request)
    {
        if (!$request->ajax()) {
            $params = $request->all();
            $size = Setting::where([])->first();
            $imageName = "";
            $thumbnail = "";
            $imagePath = '/public/media/images/';
            if ($params['image'] != "") {
                $imageName = $params['image'];
            } else if (isset($params['filename'])) {

                $imageName = uniqid() . '.' . $request->file('filename')->getClientOriginalExtension();
                $request->file('filename')->move(base_path() . $imagePath, $imageName);
                Thumbnail::createThumbnailFile($imageName, $size->width, $size->height);
            }

            if ($params['thumbnail'] != "") {
                $thumbnail = $params['thumbnail'];
            } else if (isset($params['thumbnailName'])) {
                $thumbnail = uniqid() . '.' . $request->file('thumbnailName')->getClientOriginalExtension();
                $request->file('thumbnailName')->move(base_path() . $imagePath, $thumbnail);
                Thumbnail::createThumbnailFile($thumbnail, $size->width, $size->height);
            }
            $data = [];
            if (isset($params['userId'])) {

                for ($i = 0; $i < count($params['userId']); $i++) {

                    array_push($data, $this->qetParam($params, $params['userId'][$i], $imageName, $thumbnail));
                }
                MailBox::insert($data);
            } else {
                $user = UserPlayer::where([])->get();
                for ($i = 0; $i < count($user); $i++) {

                    array_push($data, $this->qetParam($params, $user[$i]->_id, $imageName, $thumbnail));
                }
                MailBox::insert($data);
            }

            return redirect("mailBox/create")->with('success', 'Save mailBox Success');
        }
    }

    public function qetParam($params,  $userId, $imageName, $thumbnail)
    {
        $player = Players::where(['userId' => new \MongoDB\BSON\ObjectId($userId)])->first();

        return [
            'linkListName' => $params['linkListName'],
            'userId' => new \MongoDB\BSON\ObjectId($userId),
            'playerId' => new \MongoDB\BSON\ObjectId($player->_id),
            'title' => $params['title'],
            'detail' => $params['detail'],
            'coin' => isset($params['coin']) ? $params['coin'] : 0,
            'url' => isset($params['url']) ? $params['url'] : "",
            'coinActive' => isset($params['coinActive']),
            'diamond' => isset($params['diamond']) ? $params['diamond'] : 0,
            'diamondActive' => isset($params['diamondActive']),
            'mDefaultId' => isset($params['mDefaultId']) ? new \MongoDB\BSON\ObjectId($params['mDefaultId']) : "",
            'monsterActive' => isset($params['monsterActive']),
            'itemId' => isset($params['itemId']) ? new \MongoDB\BSON\ObjectId($params['itemId']) : "",
            'itemActive' => isset($params['itemActive']),
            'imageName' => $imageName,
            'thumbnail' => $thumbnail,
            'isActive' => isset($params['isActive']),
            'createAt' => new \MongoDB\BSON\UTCDateTime(now()),
            'updateAt' => new \MongoDB\BSON\UTCDateTime(now()),
        ];
    }

    public function destroy($id)
    {

        $mailBox = MailBox::find($id);

        if ($mailBox->delete()) {
            return redirect('mailBox')->with('success', trans('mailBox/message.success.destroy'));
        } else {
            return Redirect::route('mailBox')->withInput()->with('error', trans('mailBox/message.error.delete'));
        }
    }

    public function push($id)
    {

        return redirect("mailBox/{$id}/edit")
            ->with('success', 'Send mailBox Success');
    }
}

resources/views/mailBox/create.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop 
@section('content')
<section class="content-header">
    <h1>Mail Box</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('malls') }}"> Mail Box</a></li>
        <li class="active">Edit</li>
    </ol>
</section>


@if ($message = Session::get('success'))
<section class="content paddingleft_right15">
    <div class="row">   
        <div class="panel panel-success filterable">
                <div class="panel-heading">
                    <h3 class="panel-title">{{$message}}</h3>
                </div>
        </div>
    </div>
</section>
@endif

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h4 class="panel-title">SendMail</h4>
            </div>
            <div class="panel-body">
                <form id="mailBox" action="{{ route('mailBox.store') }}" method="POST" enctype="multipart/form-data"
                    class="form-horizontal">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input type="hidden" name="linkListName" value="{{uniqid()}}" />
                    <input type="hidden" name="isActive" value="0" />
                    <input type="hidden" name="thumbnail" value="" />
                    <input type="hidden" name="image" value="" />
                    <input type="hidden" name="checkImage" value="" />
                    <fieldset>
                    @include('mailBox.field')
                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</section>

@stop 

@push('more_scripts')
<script>

$(".save").on("click", function(e){
    e.preventDefault();
   
    $.ajax({
            url: "https://gaming.inmall.asia/2019/api/v1/mailBox/sendMailBox",
            method: 'POST',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data:  JSON.stringify({
                listUser:($("select[name='userId[]']").val()!=null)?$("select[name='userId[]']").val():[],
                title:$("input[name='title']").val(),
                detail:$("textarea[name='detail']").val(),
                linkListName:$("input[name='linkListName']").val(),
            }),
            success: function(data) {
                $('#mailBox').submit();
            }

        });
  
});
$(".privilegeGroups").change(function (){
    $.ajax({
            url: "{{ URL::to('api/privilegeDefault/searchByPrivilegeGroups') }}",
            method: 'GET',
            data: "privilegeGroupId="+$(this).val(),
            success: function(data) {
             $("select[name='privilegeDefaults'").html('');
             $("select[name='privilegeDefaults'").html(data.options);
            }
        });
})
$(".searchPlayer").click(function (){
        
        $.ajax({
            url: "{{ URL::to('api/privilegeDefaultPlayers/searchPlayer') }}",
            method: 'GET',
            data: "privilegeDefaultId="+$("#privilegeDefaults").val(),
            success: function(data) {
             $("select[name='userId[]']").html('');
             $("select[name='userId[]']").html(data.options);
            }
        });
        
})

 
$("select[name='mall']").change(function(){
    $.ajax({
        url: "{{ URL::to('mallFloors/searchByMall') }}",
        method: 'GET',
        data: "mallId="+$(this).val(),
        success: function(data) {
        
        $("select[name='mallFloor']").html('');
        $("select[name='mallFloor']").html(data.options);
        
        }
    });
});

$("select[name='mallFloor']").change(function(){
    $.ajax({
        url: "{{ URL::to('shops/searchByMallFloor') }}",
        method: 'GET',
        data: "mallFloorId="+$(this).val(),
        success: function(data) {
        $("select[name='shop']").html('');
        $("select[name='shop']").html(data.options);
        
        }
    });
});

$("select[name='shop']").change(function(){

    $.ajax({
        url: "{{ URL::to('api/news/searchByShop') }}",
        method: 'GET',
        data: "shopId="+$(this).val(),
        success: function(data) {
        $("select[name='news']").html('');
        $("select[name='news']").html(data.options);
        
        }
    });
});

$("select[name='news']").change(function(){

    $.ajax({
        url: "{{ URL::to('api/news') }}/"+$(this).val(),
        method: 'GET',
        success: function(result) {
            let news=result.data 
            $("input[name='title']").val(news.newsName.eng);
            $("textarea[name='detail']").val(news.newsDetail.eng);  
            if(news.filenameImage1!=undefined&&$("input[name='thumbnailName']").val()==""){
            $("#preview-thumbnail").css("display","block");
            $("#img-thumbnail").attr("src","/media/images/"+news.filenameImage1); 
            $("input[name='thumbnailName']").attr("disabled",true);    
            $("input[name='thumbnail']").val(news.filenameImage1);
            }

            if(news.filenameImage2!=undefined&&$("input[name='filename']").val()==""){
            $("#preview-img").css("display","block");
            $("#img").attr("src","/media/images/"+news.filenameImage2);
            $("input[name='filename']").attr("disabled",true);
            $("input[name='image']").val(news.filenameImage2);
            }
        }
    });

});

$(".searchPlayerByShop").click(function (){
    let query="";
    if($("select[name='mall']").val()!=""){
        query+="&mallId="+$("select[name='mall'").val();
    }
    if($("select[name='mallFloor']").val()!=""){
        query+="&mallFloorId="+$("select[name='mallFloor'").val();
    }

    if($("select[name='shop']").val()!=""){
        query+="&shopId="+$("select[name='shop']").val();
    }

    if($("select[name='news']").val()!=""){
        query+="&newsId="+$("select[name='news']").val();
    }
   
    $.ajax({
        url: "{{ URL::to('/api/shops/searchByPlayer') }}",
        method: 'GET',
        data: query,
        success: function(data) {
        $("select[name='userId[]'").html('');
        $("select[name='userId[]'").html(data.options);
        
        }
    });
})
</script>
@endpush

resources/views/mailBox/edit.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop 
@section('content')
<section class="content-header">
    <h1>Mail Box</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('malls') }}"> Mail Box</a></li>
        <li class="active">Edit</li>
    </ol>
</section>


@if ($message = Session::get('success'))
<section class="content paddingleft_right15">
    <div class="row">   
        <div class="panel panel-success filterable">
                <div class="panel-heading">
                    <h3 class="panel-title">{{$message}}</h3>
                </div>
        </div>
    </div>
</section>
@endif

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h4 class="panel-title">editMail</h4>
            </div>
            <div class="panel-body">
                    {!! Form::model($mailBox, ['url' => URL::to('mailBox') . '/' . $mailBox->id, 'method' => 'put', 'class' => 'form-horizontal', 'enctype'=>'multipart/form-data']) !!}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input type="hidden" name="linkListName" value="{{$mailBox->linkListName}}" />                   
                    <input type="hidden" name="isActive" value="0" />
                    <input type="hidden" name="monsterActive" value="0" />
                    <input type="hidden" name="coinActive" value="0" />
                    <input type="hidden" name="diamondActive" value="0" />
                    <input type="hidden" name="itemActive" value="0" />

                    <fieldset>
                    @include('mailBox.field')
                    </fieldset>
                
                    {!! Form::close() !!}

            </div>
        </div>
    </div>
</section>

@stop 

@push('more_scripts')
<script>

$(".pushMail").on("click", function(e){
    $.ajax({
            url: "https://gaming.inmall.asia/2019/api/v1/mailBox/sendMailBox",
            method: 'POST',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data:  JSON.stringify({
                listUser:["{{$mailBox->userId}}"],
                title:$("input[name='title']").val(),
                detail:$("textarea[name='detail']").val(),
                linkListName:$("input[name='linkListName']").val(),
            }),
            success: function(data) {
                
                window.location ="{{ url('/mailBox/push/') }}"+"/"+"{{$mailBox->id}}"
            }

        });
})
$(".save").on("click", function(e){
$('form').submit();
})

</script>
@endpush

resources/views/mailBox/index.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Mail Box Lists @parent 
@stop {{-- page level styles--}}

@section('header_styles') 
@stop {{-- Page content --}} 
@section('content')
<section class="content-header">
    <h1>Mail Box</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li><a href="#"> MailBox</a></li>
        <li class="active">MailBox Lists</li>
    </ol>
</section>
<section class="content paddingleft_right15">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable ">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title pull-left">Mail Box</h3>
                    <div class="pull-right">
                    <a href="{{ URL::to('mailBox/create') }}" class="btn btn-primary btn-sm" id="addButton">Add new</a>
                    </div>
                </div>

                <div class="panel-body table-responsive">
                    <table class="table" id="table">
                        <thead>
                            <tr class="filters">
                             <th>Linklistname</th>
                             <th>Email</th>
                             <th>Title</th>
                             <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($mailBox as $row)
                            <tr>
                                <td>{{$row->linkListName}}</td>
                                <td>{{$row->user->email}}</td>
                                <td>{{$row->title}}</td>
                                <td>
                                        <a href="{{{ URL::to('mailBox/' . $row->id . '/edit' ) }}}">
                                            <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="Edit"></i>
                                        </a>
                                    
                                        <a href="#" data-toggle="modal" data-target="#delete_confirm" data-id="{{ route('mailBox.destroy', collect($row)->first()) }}">
                                        <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete user"></i>
                                        </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- Modal for showing delete confirmation -->
                    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="user_delete_confirm_title">
                                        Delete
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure to delete this?
                                </div>
                                <div class="modal-footer">
                                {!! Form::open(['method' => 'DELETE']) !!}
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                                    <button type="submit" class="btn btn-danger">Delete</a>
                                {!! Form::close() !!}  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>



@stop {{-- page level scripts --}} 
@section('footer_scripts')
<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/jquery.dataTables.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
<script>
    $(document).ready(function() {
        $('#table').dataTable();
    });
    $('#delete_confirm').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget)
        let $recipient = button.data('id');
        console.log("recipient: ",$recipient);

        let modal = $(this);
        modal.find('.modal-footer form').prop("action",$recipient);
    })
</script>

@yield('modalScripts')
@stop