routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\ItemCategorys;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
// Route::get('/register', function () {
//   // abort(404);
// });

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/excel', 'UserController@excel')->name('user.excel');
Route::get('/report/monstersDefault', 'MonstersDefaultController@report')->name('report.monstersDefault');
Route::get('/monstersDefault/excel', 'MonstersDefaultController@excel')->name('monstersDefault.excel');
Route::get('/monstersDefault/{id}/player', 'MonstersDefaultController@player')->name('player');
Route::get('/report/wildMonsters', 'WildMonstersController@report')->name('report.wildMonsters');
Route::get('/wildMonsters/excel', 'WildMonstersController@excel')->name('wildMonsters.excel');
Route::get('/wildMonsters/excelIndex', 'WildMonstersController@excelIndex')->name('wildMonsters.excelIndex');
Route::get('/wildMonstersInstantiate/excel', 'WildMonstersController@excelInstantiate')->name('monstersInstantiate.excel');
Route::get('/report/monstersInstantiate', 'WildMonstersController@instantiate')->name('report.monstersInstantiate');
Route::get('/report/itemPlayer', 'ItemPlayerController@report')->name('report.itemPlayer');
Route::get('/report/itemCoupon', 'ItemPlayerController@itemCoupon')->name('report.itemCoupon');
Route::get('/report/itemCouponExcel', 'ItemPlayerController@itemCouponExcel')->name('itemCoupon.excel');
Route::get('/itemPlayer/excel', 'ItemPlayerController@excel')->name('itemPlayer.excel');
Route::get('/report/monsterInShop', 'MonstersInShopController@report')->name('report.monsterInShop');
Route::get('/monsterInShop/excel', 'MonstersInShopController@excel')->name('monsterInShop.excel');
Route::post('/itemPlayer/search', 'ItemPlayerController@search')->name('search');
Route::get('/privilegeShops/excel', 'PrivilegeShopsController@excel')->name('privilegeShops.excel');
Route::post('/privilegeShops/search', 'PrivilegeShopsController@search')->name('privilegeShops.search');
Route::get('/shops/excelPrivilegeShops', 'ShopsController@excelPrivilegeShops')->name('shops.excelPrivilegeShops');
Route::get('/shops/excelPromotion', 'ShopsController@excelPromotion')->name('shops.excelPromotion');
Route::post('/shops/searchIndex', 'ShopsController@searchIndex')->name('shops.searchIndex');
Route::get('/playerLogs/excel', 'PlayerLogsController@excel')->name('playerLogs.excel');
Route::get('/activities/calender', 'ActivitiesController@calender')->name('activities.calender');
Route::get('/activities/{id}/view', 'ActivitiesController@view')->name('activities.view');
Route::get('/couponItem/importCsv', 'CouponItemController@importCsv')->name('couponItem.importCsv');
Route::post('/couponItem/storeCsv', 'CouponItemController@storeCsv')->name('couponItem.storeCsv');
Route::resource('playerLogs', 'PlayerLogsController');
Route::resource('itemPlayer', 'ItemPlayerController');
Route::resource('players', 'PlayersController');
Route::resource('itemDefaults', 'ItemDefaultsController');
Route::resource('itemCategorys', 'ItemCategorysController');
Route::post('/news/search', 'NewsController@search')->name('news.search');
Route::resource('news', 'NewsController');
Route::get('/news/push/{id}', 'NewsController@push')->name('push');
Route::resource('newsTypes', 'NewsTypesController');
Route::resource('malls', 'MallsController');
Route::resource('shops', 'ShopsController');
Route::resource('shopAds', 'ShopAdsController');
Route::resource('shopAsserts', 'ShopAssertsController');
Route::resource('shopCategories', 'ShopCategoriesController');
Route::resource('zoneTypes', 'ZoneTypeController');
Route::resource('stickerStores', 'StickerStoreController');
Route::resource('authenTypes', 'AuthenTypeController');
Route::resource('mallFloors', 'MallFloorsController');
Route::resource('costumes', 'CostumesController');
Route::resource('digitalBoardAsserts', 'DigitalBoardAssertsController');
Route::resource('wildItems', 'WildItemsController');
Route::resource('wildMonsters', 'WildMonstersController');
Route::resource('testUpload', 'TestUploadController');
Route::resource('privilegeDefaults', 'PrivilegeDefaultsController');
Route::resource('monstersDefaultsTypes', 'MonstersDefaultsTypesController');
Route::resource('monstersDefault', 'MonstersDefaultController');
Route::resource('privilegeGroups', 'PrivilegeGroupsController');
Route::resource('privilegeShops', 'PrivilegeShopsController');
Route::resource('monsterInShop', 'MonstersInShopController');
Route::resource('user', 'UserController');
Route::resource('mailBox', 'MailBoxController');
Route::get('/mailBox/push/{id}', 'MailBoxController@push')->name('push');
Route::resource('digitalBoard', 'DigitalBoardController');
Route::delete('/digitalBoard/deleteThumbnail/{id}/{image}/{type}', 'DigitalBoardController@deleteThumbnail');
Route::resource('monstersPlayer', 'MonstersPlayerController');
Route::get('/privacyPolicy/view/', 'PrivacyPolicyController@view')->name('privacyPolicy.view');
Route::get('/privacyPolicy/{version}/setupCurrent', 'PrivacyPolicyController@setupCurrent')->name('privacyPolicy.setupCurrent');
Route::resource('privacyPolicy', 'PrivacyPolicyController');
Route::resource('device', 'DeviceController');
Route::get('device/{id}/view', 'DeviceController@view')->name('view');
Route::resource('loginReward', 'LoginRewardController');
Route::get('thumbnail/edit', 'ThumbnailImageController@edit')->name('edit');
Route::put('thumbnail/setImage', 'ThumbnailImageController@setImage')->name('setImage');
Route::get('giveMonster/edit', 'GiveMonsterController@edit')->name('edit');
Route::resource('giveMonster', 'GiveMonsterController');
Route::resource('thumbnail', 'ThumbnailImageController');
Route::resource('roles', 'RoleController');
Route::get('genCouponPassword/{json}', function ($json) {
    $code = "{\"\couponPassword\"\:{$json}";
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});

Route::get('genCouponPassword/{json}', function ($json) {
    $code = '{"couponPassword":"' . $json . '"}';
    \QrCode::size(250)
        ->format('png')
        ->generate($json);
    return view('qrCode', compact('code'));
});
Route::get('genQrCode/{code}', function ($code) {

    \QrCode::size(250)
        ->format('png')
        ->generate($code);
    return view('qrCode', compact('code'));
});

Route::resource('networkAccess', 'NetworkAccessController');
Route::resource('ipAccess', 'IpAccessController');
Route::resource('partnerTypes', 'PartnerTypesController');
Route::resource('activities', 'ActivitiesController');
Route::delete('couponItem/destroyItemPlayer/{id}', 'CouponItemController@deleteItemPlayer')->name('couponItem.destroyItemPlayer');
Route::get('couponItem/createMultipleCode', 'CouponItemController@createMultipleCode')->name('couponItem.createMultipleCode');
Route::post('/couponItem/storeMultipleCode', 'CouponItemController@storeMultipleCode')->name('couponItem.storeMultipleCode');
Route::resource('couponItem', 'CouponItemController');

app/Models/ShopAds.php
<?php

namespace App\Models;

// use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use App\Helper\MongoModel;
use App\Helper\NestedMongoModel;

class ShopAds extends MongoModel
{
    protected $connection = 'mongodb';
    protected $collection = 'shopAds';
    protected $guarded = [];
    
    public static function SCHEMAS()
    {
        return [
            'shopAdsName' => ['type' => 'array(string)' ],
            'shopAdsImage' => ['type' => 'string' ],
            'shopAdsImageLists' => ['type' => 'array(string)' ],
        ];
    }

    public static function queryShopAds(){

        $queryShopAds= ShopAds::where([])->get();
        $shopAdses=[];
        
        if($queryShopAds){
            foreach($queryShopAds as $shopAds){
                $shopAdses[$shopAds->id]=$shopAds->shopAdsName['eng'];
            }
        }
     
       return $shopAdses;
    }
}

app/Http/Controllers/ShopAdsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use App\Models\ShopAds;
use App\Http\Requests\ShopAdsRequest;
use App\Helper\ConvertValueLanguages;

class ShopAdsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:Mall_Resource');
    }

    public function index()
    {
        $shopAds = ShopAds::all();

        return view('shopAds.index', compact('shopAds'));
    }

    public function create()
    {
        $shopAdsImages = null;
        return view('shopAds.create', compact('shopAdsImages'));
    }

    public function store(ShopAdsRequest $request)
    {
        $shopAd = new ShopAds($request->all());

        $imageFile1 = $shopAd->shopAdsImageLists;
        $imageFile1 = $shopAd->shopAdsImage;
        $imagePath1 = '/public/media/images/';

        if (isset($imageFile1)) {
            $imageName1 = uniqid() . '.' . $request->file('shopAdsImage')->getClientOriginalExtension();
            $shopAd->shopAdsImage = $imageName1;
            $request->file('shopAdsImage')->move(base_path() . $imagePath1, $imageName1);
        } else {
            $shopAd->shopAdsImage = "";
        }

        $imageFile = $shopAd->imageSlots;
        $imagePath = '/public/media/images/';
        if (isset($imageFile)) {
            $slots = [];
            foreach ($imageFile as $photo) {
                $imageName = uniqid() . '.' . $photo->getClientOriginalExtension();
                $photo->move(base_path() . $imagePath, $imageName);
                array_push($slots, $imageName);
            }
            $shopAd->shopAdsImageLists = $slots;
        } else {
            $shopAd->shopAdsImageLists = [];
        }

        $shopAd->shopAdsName = ConvertValueLanguages::convertData($shopAd->shopAdsName);

        if ($shopAd->save()) {
            return redirect('shopAds')->with('success', trans('shopAds/message.success.create'));
        } else {
            return Redirect::route('shopAds')->withInput()->with('error', trans('shopAds/message.error.create'));
        }
    }

    public function edit(ShopAds $shopAd)
    {
        $shopAdsImages = $shopAd->shopAdsImage;
        $shopAdsImagelist = $shopAd->shopAdsImageLists;
        return view('shopAds.edit', compact('shopAd', 'shopAdsImages', 'shopAdsImagelist'));
    }

    public function update(ShopAdsRequest $request, ShopAds $shopAd)
    {
        if ($shopAd->update($request->all())) {

            $imageFile1 = $request->shopAdsImage;
            $imagePath1 = '/public/media/images/';

            if (isset($imageFile1)) {
                $imageName1 = uniqid() . '.' . $request->file('shopAdsImage')->getClientOriginalExtension();
                $shopAd->update(['shopAdsImage' => $imageName1]);
                $request->file('shopAdsImage')->move(base_path() . $imagePath1, $imageName1);
            }
            $imageFile = $request->imageSlots;
            $imagePath = '/public/media/images/';
            if (isset($imageFile)) {
                $slots = [];
                foreach ($imageFile as $photo) {
                    $imageName = uniqid() . '.' . $photo->getClientOriginalExtension();
                    $photo->move(base_path() . $imagePath, $imageName);
                    array_push($slots, $imageName);
                }
                $shopAd->update(['shopAdsImageLists' => $slots]);
            }


            $shopAd->update(['shopAdsName' => ConvertValueLanguages::convertData($shopAd->shopAdsName)]);

            return redirect('shopAds')->with('success', trans('shopAds/message.success.update'));
        } else {
            return Redirect::route('shopAds')->withInput()->with('error', trans('shopAds/message.error.update'));
        }
    }

    public function destroy($id)
    {
        $shopAd = ShopAds::find($id);

        if ($shopAd) {
            $shopAd->delete();
            return redirect('shopAds')->with('success', trans('shopAds/message.success.destroy'));
        } else {
            return Redirect::route('shopAds')->withInput()->with('error', trans('shopAds/message.error.delete'));
        }
    }

    public function data()
    {
        $models = ShopAds::get(['id', 'first_name', 'last_name', 'email', 'created_at']);

        return DataTables::of($models)
            ->editColumn('created_at', function (ShopAds $models) {
                return $user->created_at->diffForHumans();
            })
            ->addColumn('status', function ($user) {
                if ($activation = Activation::completed($user)) {
                    return 'Activated';
                } else {
                    return 'Pending';
                }
            })
            ->addColumn('actions', function ($user) {
                $actions = '<a href=' . route('users.show', $user->id) . '><i class="livicon" data-name="info" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="view user"></i></a>
                            <a href=' . route('users.edit', $user->id) . '><i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="update user"></i></a>';
                if ((Sentinel::getUser()->id != $user->id) && ($user->id != 1)) {
                    $actions .= '<a href=' . route('users.confirm-delete', $user->id) . ' data-id="' . $user->id . '" data-toggle="modal" data-target="#delete_confirm"><i class="livicon" data-name="user-remove" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete user"></i></a>';
                }
                return $actions;
            })
            ->rawColumns(['actions'])
            ->make(true);
    }
}

resources/views/shopAds/create.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop 
@section('content')
<section class="content-header">
    <h1>Shop Ads</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('shopAds') }}"> Shop Ads</a></li>
        <li class="active">Add new</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Add New</h3>
            </div>
            <div class="panel-body">
                <form id="monstersDefaultForm" action="{{ route('shopAds.store') }}" method="POST" enctype="multipart/form-data"
                    class="form-horizontal">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <fieldset>
                    @include('shopAds.field')
                    </fieldset>

                </form>

            </div>
        </div>
    </div>
    <!--row end-->
</section>

@stop

resources/views/shopAds/edit.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Add User @parent 
@stop 
@section('content')
<section class="content-header">
    <h1>Shop Ads</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
        </li>
        <li><a href="{{ URL::to('shopAds') }}"> Shop Ads</a></li>
        <li class="active">Edit</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-info filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Edit</h3>
            </div>
            <div class="panel-body">
                {!! Form::model($shopAd, ['url' => URL::to('shopAds') . '/' . $shopAd->id, 'method' => 'put', 'class' => 'form-horizontal', 'enctype'=>'multipart/form-data']) !!}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                    <fieldset>
                    @include('shopAds.field')
                    </fieldset>

                {!! Form::close() !!}

            </div>
        </div>
    </div>
</section>

@stop

resources/views/shopAds/field.blade.php
@component('components.multiLangField',[
    'header'=>'Shop Ads Names',
    'field'=>'shopAdsName',
    'icon'=>'livicon'
    ])
@endcomponent

<h4>Multi</h4>
<div class="row">
    <div class="col-md-2 col-xs-offset-2">
        @if(!empty($shopAdsImages))
        <div class="fileinput-preview  thumbnail" data-trigger="fileinput" style="width: 210px; height: 160px;">
            <img src="{{URL::to('media/images/'.$shopAdsImages)}}" class="img-responsive" alt="$field"  style="width: 200px; height: 150px;">
        </div>
        @endif
    </div> 
    @if(!empty($shopAdsImagelist))    
    <div class="col-md-6 col-xs-offset-2">
        <div class="form-group row">
                <label for="inputUsername" class="col-md-3 control-label">shop Ads Image Lists</label>
                @component('components.modal',['id'=>uniqid(),'title'=>'ImageSlots'])
                    @slot('content')
                    @foreach($shopAdsImagelist as $photo)
                        <img src="{{URL::to('media/images/'.$photo)}}" style="width: 100px; height: 70px" />
                    @endforeach
                    @endslot
                @endcomponent
        </div>   
    </div> 
    @endif    
</div>
<div class="row">
    <div class="col-md-6">
        @component('components.inputField',[
            'type'=>'file',
            'icon'=>'text',
            'label'=>'Shop Ads Image',
            'field'=>'shopAdsImage',
            'value'=>null,
            'attribute'=>['class'=>'form-control']
        ])
        @endcomponent
    </div>
    <div class="col-md-6">
        @component('components.inputField',[
            'type'=>'file',
            'icon'=>'text',
            'label'=>'Shop Ads Image Lists (Multiple)',
            'field'=>'imageSlots[]',
            'value'=>null,
            'attribute'=>['class'=>'form-control','multiple'=>true]
        ])
        @endcomponent
    </div>
</div>


<div class="form-group">
    <div class="col-md-12 text-right">
        <button type="submit" class="btn btn-responsive btn-primary btn-sm">Submit</button>
    </div>
</div>

resources/views/shopAds/index.blade.php
@extends('layouts/default') {{-- Page title --}} 
@section('title') Shop Ads Lists @parent 
@stop {{-- page level styles--}}

@section('header_styles') 
@stop {{-- Page content --}} 
@section('content')
<section class="content-header">
    <h1>Shop Ads</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li><a href="#"> Shop Ads</a></li>
        <li class="active">Shop Ads Lists</li>
    </ol>
</section>
<section class="content paddingleft_right15">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info filterable ">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title pull-left">Shop Ads</h3>
                    <div class="pull-right">
                    <a href="{{ URL::to('shopAds/create') }}" class="btn btn-primary btn-sm" id="addButton">Add new</a>
                    </div>
                </div>

                <div class="panel-body table-responsive">
                    <table class="table" id="table">
                        <thead>
                            <tr class="filters">
                                <th>Shop Ads Name</th>
                                <th>Shop Ads Image</th>
                                <th>Shop Ads Image Lists</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($shopAds as $row)
                            <tr>
                                <td>{{ $row->shopAdsName['eng'] }}</td>
                                <td><img src="{{URL::to('media/images/'.$row->shopAdsImage)}}" style="width: 100px; height: 70px" /></td>
                                <td>

                                @if(isset($row->shopAdsImageLists))
                                @component('components.modal',['id'=>uniqid(),'title'=>'Image Lists'])
                                    @slot('content')
                                    @foreach($row->shopAdsImageLists as $photo)
                                        <img src="{{URL::to('media/images/'.$photo)}}" style="width: 100px; height: 70px" />
                                    @endforeach
                                    @endslot
                                @endcomponent
                                @endif
                                </td>
                                <td>
                                    <a href="{{{ URL::to('shopAds/' . $row->id . '/edit' ) }}}">
                                        <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="Edit"></i>
                                    </a>
                                </a>
                                    <a href="#" data-toggle="modal" data-target="#delete_confirm"  data-id="{{ route('shopAds.destroy', collect($row)->first()) }}">
                                        <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete user"></i>
                                        <!-- {{route('shopAds.destroy', collect($row)->first() )}} -->
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- Modal for showing delete confirmation -->
                    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="user_delete_confirm_title">
                                        Delete
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure to delete this?
                                </div>
                                <div class="modal-footer">
                                {!! Form::open(['method' => 'DELETE']) !!}
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                                    <button type="submit" class="btn btn-danger">Delete</a>
                                {!! Form::close() !!}  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>



@stop {{-- page level scripts --}} 
@section('footer_scripts')
<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/jquery.dataTables.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
<script>
    $(document).ready(function() {
        $('#table').dataTable({
            "pageLength": 50
        });
    });
    $('#delete_confirm').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget)
        let $recipient = button.data('id');
        console.log("recipient: ",$recipient);

        let modal = $(this);
        modal.find('.modal-footer form').prop("action",$recipient);
    })

</script>







@stop